title: Treasure Data Debugger
description: Modern Chrome DevTools extension for debugging Treasure Data requests
# Exclude from processing
exclude:
  - node_modules
  - vendor

# Include
include:
  - _layouts

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
